export const fonts = {
  1: { name: "Kiss Me or Not" },
  2: { name: "#9Slide05 Agile Script Calligraphy Regular" },
  3: { name: "#9Slide03 Nanami Rounded Light" },
  4: { name: "#9Slide06 SVNJonitha Script" },
  5: { name: "#9Slide05 Brannboll Ny" },
  6: { name: "#9Slide06 SVNSharpen" },
  7: { name: "Autumn in November" },
  8: { name: "Pacifico Regular" },
  9: { name: "Meila Line Bold" },
  10: { name: "Smoothie Shoppe" },
  11: { name: "SVN-Weekdays Santtuy Regular" },
  12: { name: "SVN-The Wild Things Script" },
  13: { name: "SVN-Beachwood Script" },
  14: { name: "Shark Blindate" },
  15: { name: "Bali SVN-Bali Script" },
  16: { name: "SVN-Bistro Script" },
  17: { name: "Funky Baby" },
  18: { name: "dearheart" },
  19: { name: "Lobster Regular" },
  20: { name: "Amatic SC", fontWeight: "bold" },
  21: { name: "Bangers Regular" },
  22: { name: "Sacramento" },
  23: { name: "Nerko One Regular" },
  24: { name: "Yellowtail Regular" },
  25: { name: "Roller Skates Regular" },
  26: { name: "Mocha Frappuccino", fontWeight: "bold" },
  27: { name: "Andala Script Regular" },
  28: { name: "Autumn Moon" },
  29: { name: "Try Happiness Demo" },
  30: { name: "HelloConnor-Regular" },
  31: { name: "Carat Regular" },
  32: { name: "Lora" },
  33: { name: "Hello Minimalist" },
  34: { name: "" },
  35: { name: "Riverdale Regular" },
  36: { name: "BreakSticker-Regular" },
  37: { name: "#9Slide05 SVNVery Berry Regular" },
  38: { name: "GhostBuster-Regular" },
  39: { name: "HauntedBloodRegular" },
  40: { name: "GhostCastle-Regular" },
  41: { name: "WitchAdventure" },
  42: { name: "Sweet Bones Regular" },
  43: { name: "SpookyVampire" },
  44: { name: "CreepyNight-Regular" },
  45: { name: "Dancing Script" },
  46: { name: "#9Slide03 IcielNovecento sans Med" },
  47: { name: "Canterbury Regular" },
  48: { name: "Wild Sage" },
  49: { name: "BestieForever-Regular" },
  50: { name: "Sweet Kisses" },
};

export const Regex = {
  SpecialChars: /[`~!@#$%^&*()_|+\-=?;:'",.<>{}[]\\\/]/gi,
  Username: /^(?![_.])(?![\d])(?!.*\.\.)(?!.*\.$)(?=.*[a-z])[a-z0-9._]{3,}$/,
  Email: /^[A-Za-z0-9._+-]+@[A-Za-z0-9]+\.[A-Z|a-z]{2,}$/,
  Password:
    /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[0-9a-zA-Z`~!@#$%^&*()-_+={}[\]|\\'";:/?>.<,]{8,}$/,
  hasSpecialChars: /[^a-zA-Z\d\s:,.-]/g,
};

export const isSpecialChars = (str) => {
  const specialChars = /[`!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?~ •]/;
  return specialChars.test(str);
};
